# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate the effective transcript lengths. This is the mean number of
#' positions in the transcript the fragment could map to.
#'
#' @param txlength The sequence lengths for each transcript.
#' @param rdlengths The length of all mapped fragments. Mapped length of the
#'  read after accounting for mismatches and indels.
#' @return The effective lengths.
#' @export
effective_lengths <- function(txlengths, rdlengths) {
    .Call(`_mbtools_effective_lengths`, txlengths, rdlengths)
}

em_count <- function(txreads, txlengths, ntx, nr, maxit = 1000L, reltol = 0.01, abstol = 0.01) {
    .Call(`_mbtools_em_count`, txreads, txlengths, ntx, nr, maxit, reltol, abstol)
}

