# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

effective_lengths <- function(txlengths, rdlengths) {
    .Call(`_mbtools_effective_lengths`, txlengths, rdlengths)
}

em_count <- function(txreads, txlengths, ntx, nr, maxit = 1000L, cutoff = 0.01) {
    .Call(`_mbtools_em_count`, txreads, txlengths, ntx, nr, maxit, cutoff)
}

